services:
  backend:
    image: dedukr/backend:latest
    build:
      context: ./backend
    command: gunicorn backend.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    image: dedukr/frontend:latest
    build:
      context: ./frontend
    volumes:
      - frontend_build:/frontend/build/

  nginx:
    image: dedukr/nginx:latest
    build: 
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - frontend_build:/var/www/frontend/
    depends_on:
      - backend
      - frontend

volumes:
  frontend_build:
